#SERVER
server.local=false
server.test=false
server.daoautoupdater=false
server.sv=1
server.name=NRO
server.ip=163.61.182.199
server.port=14445
#server.sv1=NroLight:fw.patus.tech:14449:0,0,0
server.waitlogin=3
server.maxperip=20
server.maxplayer=1000
server.expserver=3

#DATABASE
database.driver=com.mysql.jdbc.Driver
database.host=127.0.0.1
database.port=3306
database.name=team2026
database.user=nro
database.pass=nropass
database.min=2
database.max=10
database.lifetime=1800000
